version: '3.1'
services:
  web:
    # build: .
    image: alerta/alerta-web
    volumes:
      - $PWD/config/alertad.conf.example:/app/alertad.conf
      - $PWD/config/alerta.conf.example:/app/alerta.conf
      - $PWD/config/config.js.example:/web/config.js
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - DEBUG=1  # remove this line to turn DEBUG off
      # - BASE_URL=/alerta/api  # => web_url=/alerta
      - AUTH_REQUIRED=True
      - ADMIN_USERS=admin@alerta.io,devops@alerta.io
      # - ADMIN_USERS=admin@alerta.io
      # - ADMIN_PASSWORD=password
      - ADMIN_KEY=demo-admin-key
      - PLUGINS=reject,blackout,normalise,enhance
      - INSTALL_PLUGINS=normalise,enhance
    restart: always
