version: '3'

services:
  sut:
    build:
      context: .
      args:
        VCS_REF: ${VCS_REF}
        VERSION: ${VERSION}
    # image: alerta/alerta-web
    ports:
      - 8080
    depends_on:
      - db
    environment:
      # - DEBUG=1  # remove this line to turn DEBUG off
      - DATABASE_URL=postgres://postgres:postgres@db:5432/monitoring
      - AUTH_REQUIRED=tRuE
      - ADMIN_USERS=admin@alerta.io,devops@alerta.io # default password: alerta
      - ADMIN_KEY=demo-key
      - ADMIN_KEY_MAXAGE=31536000 # 1 year in seconds
      - PLUGINS=reject,blackout,normalise,enhance

  tester:
    image: curlimages/curl:latest
    volumes:
      - ./wait-for:/wait-for
      - ./tests.sh:/tests.sh
    depends_on:
      - sut
    command: sh -c './wait-for sut:8080 -t 240 -- ./tests.sh'

  db:
    image: postgres
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: monitoring
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

