version: '3.1'
services:
  web:
    # build: .
    image: alerta/alerta-web
    # volumes:
      # - $PWD/config/alertad.conf.example:/app/alertad.conf
      # - $PWD/config/alerta.conf.example:/app/alerta.conf
      # - $PWD/config/config.json.example:/web/config.json
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      # - DEBUG=1  # remove this line to turn DEBUG off
      - DATABASE_URL=postgres://postgres:postgres@db:5432/monitoring
      - AUTH_REQUIRED=True
      - ADMIN_USERS=admin@alerta.io,devops@alerta.io
      - ADMIN_PASSWORD=super-secret # default is "alerta"
      - ADMIN_KEY=demo-key  # assigned to first user in ADMIN_USERS
      - ADMIN_KEY_MAXAGE=500
      # - PLUGINS=remote_ip,reject,heartbeat,blackout,normalise,enhance
    restart: always
  db:
    image: postgres
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: monitoring
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: always
