# Default values for alerta.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: alerta/alerta-web
  tag: 8.1.0
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - alerta.example.com
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 1
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

extraSecretMounts: []
  # - name: secret-files
  #   mountPath: /etc/secrets
  #   subPath: ""
  #   secretName: alertmanager-secret-files
  #   readOnly: true

# alertaAdminPassword: "" # if not provided will be randomly generated
# alertaAdminUsers: # list of email addresses
#   - "admin@alerta.io"
# alertaAdminKey: "<your_api_key_here>"
# alertaApiKey: "<your_api_key_here>" # you probably want to set this to the same value as 'alertaAdminKey'

# Alerta plugins to install
# alertaInstallPlugins:
#   - normalise
#   - enhance

# ref: http://docs.alerta.io/en/latest/configuration.html
# alertaConfig:
#   DEBUG: "True"
#   AUTH_REQUIRED: "True"
#   PLUGINS: "['normalise', 'enhance']"
#   DATABASE_URL: "" # provide db url here if you're not using the postgres chart

# ref: http://docs.alerta.io/en/latest/webui.html
# alertaWebUIConfig: |
#   // contents of config.js
#   'use strict';
#   angular.module('config', [])
#     .constant('config', {
#       'endpoint'    : "/api",
#       'provider'    : "basic"
#     })
#     .constant('colors', {});

postgresql:
  enabled: true
  postgresqlUsername: alerta
  postgresqlDatabase: monitoring
  postgresqlPassword: "changeme" # provide a password here, otherwise it will be randomly generated inside postgresql helm chart and will not be available as a variable in the alerta helm chart
  persistence:
    enabled: true
    size: 10Gi
